In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_excel(r"E:\PythonCore\datafiles\Social_Network_Ads.xlsx")

In [4]:
X = df.iloc[:,[0,1]].values
y = df.iloc[:,-1].values
print(X.shape, y.shape)

(284, 2) (284,)


In [5]:
s = StandardScaler()
# The standard score of a sample `x` is calculated as:
# z = (x - u) / s

In [6]:
X_sc = s.fit_transform(X)

In [7]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=1)
pca_data = pca.fit_transform(X_sc)

In [11]:
pca_data.shape

(284, 1)

In [12]:
pca.components_

array([[0.70710678, 0.70710678]])

In [13]:
pca.explained_variance_ratio_

array([0.54937036])

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [15]:
X_train, X_test, y_train, y_test = train_test_split(pca_data,y,test_size=0.2, random_state=64)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(227, 1) (57, 1) (227,) (57,)


In [16]:
model = LogisticRegression(solver='lbfgs')
model.fit(X_train, y_train)
yhat = model.predict(X_test)

In [19]:
accuracy_score(y_test, yhat)

0.8245614035087719

In [20]:
#Use model to predict if these people will purchase or not purchase
temp = np.array([[42, 125000], [25,60000]])
temp.shape

(2, 2)

In [21]:
model.predict(pca.transform(s.transform(temp))) # Correct input is to transform data

array([1, 0], dtype=int64)

## 2nd example

In [22]:
wine = pd.read_csv(r"E:\PythonCore\datafiles\wine.csv")

In [23]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [24]:
wine.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [25]:
wine['Customer_Segment'].value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [26]:
#1, Split data X, y
#2. standard scaling
wine_X = wine.iloc[:,:-1].values
wine_y = wine.iloc[:,-1].values
print(wine_X.shape, wine_y.shape)

(178, 13) (178,)


In [40]:
sc = StandardScaler()
wine_X_sc = sc.fit_transform(wine_X)
wine_X_sc.shape

(178, 13)

In [63]:
wine_pca = PCA(3)
wine_pca_data = wine_pca.fit_transform(wine_X_sc)
wine_pca_data.shape

(178, 3)

In [42]:
wine_pca.components_.shape

(2, 13)

In [43]:
wine_pca.components_

array([[ 0.1443294 , -0.24518758, -0.00205106, -0.23932041,  0.14199204,
         0.39466085,  0.4229343 , -0.2985331 ,  0.31342949, -0.0886167 ,
         0.29671456,  0.37616741,  0.28675223],
       [-0.48365155, -0.22493093, -0.31606881,  0.0105905 , -0.299634  ,
        -0.06503951,  0.00335981, -0.02877949, -0.03930172, -0.52999567,
         0.27923515,  0.16449619, -0.36490283]])

In [44]:
wine_pca.explained_variance_ratio_

array([0.36198848, 0.1920749 ])

In [45]:
wine_pca_data[0,:]

array([ 3.31675081, -1.44346263])

In [53]:
# to see original data - maybe with some loss
np.set_printoptions(suppress=True)
sc.inverse_transform(wine_pca.inverse_transform(wine_pca_data[0,:])).round(2)

array([  13.95,    1.79,    2.49,   16.8 ,  112.61,    3.17,    3.42,
          0.24,    2.22,    6.15,    1.09,    3.33, 1210.96])

In [54]:
wine.iloc[0,:-1].values

array([  14.23,    1.71,    2.43,   15.6 ,  127.  ,    2.8 ,    3.06,
          0.28,    2.29,    5.64,    1.04,    3.92, 1065.  ])

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
X_train, X_test, y_train, y_test = train_test_split(wine_X,wine_y,
                                                    test_size=0.2, random_state=64)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(142, 13) (36, 13) (142,) (36,)


In [57]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train).score(X_test, y_test)

0.9444444444444444

In [65]:
X_train, X_test, y_train, y_test = train_test_split(wine_pca_data,wine_y,
                                                    test_size=0.2, random_state=64)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

model = DecisionTreeClassifier()
model.fit(X_train, y_train).score(X_test, y_test)

(142, 3) (36, 3) (142,) (36,)


0.9444444444444444